# Generated by Django 3.0.6 on 2020-06-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lising',
            new_name='listing',
        ),
    ]
